# Generated by Django 4.1.4 on 2023-02-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PJP_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('telephone', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
