# Generated by Django 4.1.4 on 2023-02-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJP_API', '0003_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
