# Generated by Django 4.1.4 on 2023-02-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJP_API', '0005_alter_ai_owner_alter_favories_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
