# Generated by Django 4.1.4 on 2023-02-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJP_API', '0006_delete_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conetnt',
            new_name='content',
        ),
    ]
