# Generated by Django 4.1.4 on 2023-02-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PJP_API', '0007_rename_conetnt_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
