# Generated by Django 4.1.3 on 2023-02-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PJP_API', '0008_alter_ai_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('im', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_images', to='PJP_API.ai')),
            ],
        ),
    ]
