# Generated by Django 4.1.3 on 2023-02-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PJP_API', '0009_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='im',
            new_name='ai',
        ),
    ]
